spring:
  datasource:
    url: jdbc:postgresql://localhost/metrix
    username: postgres
    password: postgres
scheduling:
  mode: real_time
  beginDate: 2015-01-27
  endDate: 2015-01-30
  intensity-dispersion: 0.2