spring:
  datasource:
    url: jdbc:postgresql://localhost/metrix
    username: postgres
    password: postgres
logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core: trace