spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      naming:
        physical-strategy: edu.config.infrastructure.QuotedNameStrategy
logging:
  level:
    org.hibernate.SQL: DEBUG